version: 2.1

jobs:
  garden-test:
    docker:
      - image: gardendev/garden-gcloud:v0.9.7
    steps:
      - checkout
      - setup_remote_docker
      - configure_kubectl_context
      - run:
          name: Test project
          command: garden test --logger-type=basic --env=dev-1
  garden-test-ee:
    docker:
        # TODO: pin to specific version
      - image: gardendev/garden-ee-gcloud:latest
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - checkout
      - configure_kubectl_context
      - run:
          name: Test project
          command: garden test --logger-type=basic --env=dev-1-ee
workflows:
  version: 2
  test:
    jobs:
      - garden-test
      - garden-test-ee:
          context: docker

commands:
  configure_kubectl_context:
    description: Configure the kubectl context so that we can access our remote cluster
    steps:
      - run:
          name: Configure kubectl context via gloud
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project $GOOGLE_PROJECT_ID && gcloud --quiet config set compute/zone $GOOGLE_COMPUTE_ZONE
            gcloud --quiet container clusters get-credentials $GOOGLE_CLUSTER_ID --zone $GOOGLE_COMPUTE_ZONE
            gcloud --quiet auth configure-docker
